# Generated by Django 5.1.3 on 2024-12-01 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_fotografia_categario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='categario',
            new_name='categoria',
        ),
    ]
